### Http request de um get todos os membros
GET  http://localhost:3002/membros


### buscarMembrosPeloEstadoCivil(estadoCivil)
### Http request de um get todos os membros
GET  http://localhost:3002/membros/estado-civil/solteiro


### Http request de um post de membros
POST http://localhost:3002/membros
Content-Type: application/json
{
    "nome": "Filipe Carvalho de Sousa",
    "situacao": 1,
    "email": "filipecarvalhosousa@gmail.com",
    "telefone": 61981747292,
    "endereco": {
        "rua": "",
        "bairro": "",
        "cidade": "",
        "estado": "",
        "país": "Brasil"
    },
    "data_nascimento": "1991-01-25",
    "departamento": [
        {
            "titulo": "Cadetes"
        }
    ],
    "cargo": [
        {
            "titulo": "string",
            "departamento": "string"
        }
    ],
    "estado_civil": "Casado",
    "conjuge": {
        "id": 2
    },
    "data_casamento": "2022-04-03",
    "filhos": [
        {}
    ]
}